### ISSUE TITLE
code updates

### ISSUE THREAD

**Issue by Jane550** [DataExplorerUser/ActionPotentialSim#1]
I noticed that this code was last updated 4 months ago.  In the latest version dearpygui-0.8.50, there doesn't exist dearpygui.core or dearpygui.simple. I run the code I previously wrote  based on this project after the installation of dearpygui-0.8.50 and it turned out to be error: ModuleNotFoundError: No module named 'dearpygui.core', when I modified the import to 'import dearpygui.dearpygui as dpg', there still are a lot of syntax errors. So I was wondering if this whole project need to be rewritten.

<img width="481" alt="截屏2021-07-27 下午8 57 40" src="https://user-images.githubusercontent.com/45599807/127157511-be6050ed-a240-49d6-adfe-250cd0bc31cd.png">
<img width="675" alt="截屏2021-07-27 下午8 56 25" src="https://user-images.githubusercontent.com/45599807/127157517-2618424b-8460-4694-b477-ab3394ba2e26.png">

**Comment by DataExplorerUser** [comment]
Hi Jane550,
The code is compatible with Dear PyGui 0.6. The latest version of Dear PyGui has quite a few changes to the API. The code was originally written by someone else and I just hosted it for the Dear PyGui showcase. I have no intention of updating the code. If have questions about Dear PyGui, the best place is their Discord server.
Hope this clarifies it a bit.

**Comment by Jane550** [comment]
It does. Thx!
